version: '3'

services:
  neo4j:
    image: neo4j:4.4
    container_name: neo4j
    env_file:
      - ./neo4j.env
    volumes:
      - ./data/neo4j:/data
      - ./import/neo4j:/var/lib/neo4j/import
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
